### ISSUE TITLE
Amazing minimalistic and to the point 

### ISSUE THREAD

**Issue by sainiaj** [mykle1/MMM-WWI#1]
thank you for the amazing module love it!
plain and simple to the point 
i modded it little it got rid of the image part and basic information required like wind chill and wind speed
thank you ps this is the only module which actually shows wind chill 

I am located in Canada how do i change it to C celsius
Thank you

**Comment by sainiaj** [comment]
i do see it is possible but my knowledge is super limited 
i tried the css and .js file but i must be blind
https://darksky.net/dev/docs#/dev/docs#api-request-types

**Comment by mykle1** [comment]
Hi. It's nice to know that someone other than myself is using this module. I'm very glad that you like it. I just added a config option for you, "tempUnits:" can be F or C. That will take care of the temp, heat index/windchill and the dewpoint.

One point to note: In the summary/forecast at the top (3rd or 4th line) there is a temperature that will always be in F because that return from the API is text, and not a value that I can convert. Still, I think you will be happy with what I've done. At least I hope so. Peace!
